### ISSUE TITLE
picasso localize on CLI fails with fit method "lq-gpu" in version 0.9.1

### ISSUE THREAD

**Issue by mmarinriera** [jungmannlab/picasso#591]
Hi,

When I try to run the `picasso localize` via the CLI, while passing the "lq-gpu" parameter, it fails.
If I run with the default fit method, it works fine.
I have gpufit properly set up, and it works with previous versions (up to 0.8.2 that I have tried), so that shouln't be the issue.

This is the error message I get:

```
> picasso localize "/path/to/image.tif" -a lq-gpu
    ____  _____________   __________ ____ 
   / __ \/  _/ ____/   | / ___/ ___// __ \
  / /_/ // // /   / /| | \__ \\__ \/ / / /
 / _____/ // /___/ ___ |___/ ___/ / /_/ / 
/_/   /___/\____/_/  |_/____/____/\____/  
                                          
Localize - Parameters:
No       Label           Value     
Traceback (most recent call last):
  File "/home/tirf/.local/bin/picasso", line 10, in <module>
    sys.exit(main())
  File "/home/tirf/.local/share/uv/tools/picassosr/lib/python3.10/site-packages/picasso/__main__.py", line 2411, in main
    _localize(args)
  File "/home/tirf/.local/share/uv/tools/picassosr/lib/python3.10/site-packages/picasso/__main__.py", line 936, in _localize
    if gausslq.gpufit_installed:
AttributeError: module 'picasso.gausslq' has no attribute 'gpufit_installed'
```

It seems that the issue is simply a reference to a module variable that doesn't exist.

Thanks!
Miquel
